name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup c3c
        run: |
          echo "Installing c3c..."
          curl -sL "https://github.com/c3lang/c3c/releases/download/v0.8.2/c3-linux.tar.gz" -o c3.tar.gz
          # Extract archive
          tar -xzf c3.tar.gz
          
          # Move binary to /usr/local/bin (which is natively on PATH)
          sudo cp c3/c3c /usr/local/bin/c3c
          sudo chmod +x /usr/local/bin/c3c
          
          # Clean up download files
          rm -rf c3.tar.gz c3
          
          # Verify installation
          c3c --version
      - name: Build
        run: c3c build

      - name: Test
        run: c3c test
