name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup c3c
        run: |
          echo "Installing c3c..."
          curl -fsSL https://raw.githubusercontent.com/c3lang/c3c/refs/heads/master/install/install.sh | C3_VERSION=0.8.2 bash
          echo "$HOME/.c3" >> $GITHUB_PATH
          /usr/local/bin/c3c --version
      - name: Build
        run: c3c build

      - name: Test
        run: c3c test
